src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlayerRepository::class)
 */
class Player
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Team::class, inversedBy="players")
     * @ORM\JoinColumn(nullable=false)
     */
    private $team;

    /**
     * @ORM\Column(type="array")
     */
    private $Stats = [];

    /**
     * @ORM\Column(type="array")
     */
    private $Stats5 = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $last5Games = [];

    /**
     * @ORM\Column(type="integer")
     */
    private $playerId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getStats(): ?array
    {
        return $this->Stats;
    }

    public function setStats(array $Stats): self
    {
        $this->Stats = $Stats;

        return $this;
    }

    public function getStats5(): ?array
    {
        return $this->Stats5;
    }

    public function setStats5(array $Stats5): self
    {
        $this->Stats5 = $Stats5;

        return $this;
    }

    public function getLast5Games(): ?array
    {
        return $this->last5Games;
    }

    public function setLast5Games(?array $last5Games): self
    {
        $this->last5Games = $last5Games;

        return $this;
    }

    public function getPlayerId(): ?int
    {
        return $this->playerId;
    }

    public function setPlayerId(int $playerId): self
    {
        $this->playerId = $playerId;

        return $this;
    }
}

templates/btngroup.html.twig
{% if (id == name) %} <button type="button" class="btn btn-lg btn-primary btn-{{name}}">{{ btn_label }}</button>
  {% else %}<button type="button" class="btn btn-lg btn-secondary btn-{{name}}">{{ btn_label }}</button>
  {% endif %}

templates/face_a_face.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ teams.0.Stats.Team }} VS {{ teams.1.Stats.Team}} - Pronostics / Statistiques / Tendances des équipes
{% endblock %}


{% block body %}
{% include 'matchs_de_la_nuit.html.twig' %}

{% include 'navbar.html.twig' %}


<div class="container-fluid">
  <div class="row">
   <div class="col-lg-2 order-lg-first col-6  order-2  ">
      
    </div>
    <div class="col-lg-2 col-6 order-last">
     
    </div>
    <div class="col-lg-8 col-10 col-sm-12 order-fisrt mx-auto">

       {% for match in matchs %}
      {% if match.HomeTeamId == game.hometeamid %}
        {% if match.timeRemaining is defined and match.timeRemaining is not null %}
     
      
      <h3  class="whitetitle" id="cotes"> Regardez le match en live !</h3>
      <div class="form-group row " style="justify-content:space-evenly;font-size:5rem;width:100%;">
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;" href="http://nbastreams.xyz/live/{{match.id}}/"  onclick="window.open(this.href); return false;">Lien vers le match - {{teams.0.Stats.Team}} vs {{teams.1.Stats.Team}} </a>
      </div>

      {% else %}
      <h3  class="whitetitle" id="cotes"> Cotes </h3>
      <div class="form-group row " style="justify-content:space-evenly;font-size:5rem;width:100%;">
       
        {% if odds is null %}
        <p class="whitetitle" style="font-size:2rem;">Les cotes ne sont pas encore disponible... réessayez plus tard </p>
        {% elseif  app.request.cookies.get('user') is null  %}
         <div> 
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;">{{teams.0.Stats.Team}}: {{odds.1}} </a>
        </div>
        <div> 
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;">{{teams.1.Stats.Team}}: {{odds.2}} </a>
        </div>        
        <div id="alert" class="alert alert-info col-12 row" style="font-size:1.2rem;display:none" role="alert">
        <span class="col-8">Vous devez être connecté pour pouvoir enregistrer un pari !  </span>
        <a class="btn btn-success text-light col-2" href={{path('signin')}}> Se connecter </a> 
        <a class="btn btn-secondary text-light col-2" href={{path('signup')}}> S'inscrire</a> 
        </div>
        {% elseif bet_error is not empty %}
        <div> 
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;">{{teams.0.Stats.Team}}: {{odds.1}} </a>
        </div>
        <div> 
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;">{{teams.1.Stats.Team}}: {{odds.2}} </a>
        </div> 
        <div id="alert" class="alert alert-success col-12 row" style="font-size:1.2rem;" role="alert">
        <span class="col-8"> {{bet_error}}  </span></div>
        {% else %}
        <div> 
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;" href={{ path('bet', {gameId: game.GameId,outcome:1,odd:odds.1})  }}>{{teams.0.Stats.Team}}: {{odds.1}} </a>
        </div>
        <div> 
        <a class="btn btn-dark betbutton" style="color:white;font-size:1.5rem;"  href={{ path('bet', {gameId: game.GameId,outcome:3,odd:odds.2})  }}>{{teams.1.Stats.Team}}: {{odds.2}} </a>
        </div> 
        {% endif %}
      </div>
      {% endif %}
      {% endif %}
      {% endfor %}

          {% include 'intro.html.twig'%}


      <div>       
      <h3 id="equipes" class="whitetitle"> Stats des équipes </h3>
        {% include 'statarraytemplate.html.twig' with {'id': 'overall','home':teams.0.Stats,'away':teams.1.Stats, 'arrayTitle':'Stats Equipe Serie'} %}
        {% include 'statarraytemplate.html.twig' with {'id': 'last5','home':teams.0.stats5,'away':teams.1.stats5, 'arrayTitle':'Stats Playoffs'} %}
        {% include 'statarraytemplate.html.twig' with {'id': 'location','home':teams.0.statsLocation,'away':teams.1.statsLocation, 'hadvanced':teams.0.advancedStats,'aadvanced':teams.1.advancedStats, 'arrayTitle':'Stats Saison '} %}
      </div>

      <div class="" > 
      <h3 id="tendances" class="whitetitle">Tendances 5 derniers matchs</h3>
      <div class="row">
        <div class="col col-md-6">
        {% for game in teams.0.last5games|reverse %}
         <table class="table table-dark " >
          {% if game[6][4:1] == '@' %}
            {% set abv = game[6]|split(' @ ')%}
            {% set at = '@' %}
            {% else %}
            {% set abv = game[6]|split(' vs. ') %}
            {% set at = 'vs.' %}
            {% endif %}
             <tr style="justify-content:between; paddin-top:8rem; ">
              <td>
              <img style="height:3rem;"src="https://stats.nba.com/media/img/teams/logos/{{abv[0]}}_logo.svg" alt="Card image cap">
              </td><td style="position:relative;top:1rem;size:2rem;">{{ at }}</td>
              <td><img style="height:3rem;"src="https://stats.nba.com/media/img/teams/logos/{{abv[1]}}_logo.svg" alt="Card image cap">
              </td>
              <td class="card-title result " style="position:relative;{% if game[7]=='L'%}color:red;{% else %}color:lightgreen;{% endif %}">{{ game[26]}} - {{ game[26] - game[27] }}
              </td>
             </tr>
         </table>
        {% endfor %}
        </div>
       
        
        <div class="col">
       {% for game in teams.1.last5games|reverse %}
          <table class="table table-dark">
          
          {% if game[6][4:1] == '@' %}
            {% set abv = game[6]|split(' @ ')%}
            {% set at = '@' %}
            {% else %}
            {% set abv = game[6]|split(' vs. ') %}
            {% set at = 'vs.' %}
            {% endif %}
            <tr style="justify-content:space-between; paddin-top:8rem;">
              <td>
              <img style="height:3rem;"src="https://stats.nba.com/media/img/teams/logos/{{abv[0]}}_logo.svg" alt="Card image cap">
              </td><td style="position:relative;top:1rem;size:1.3rem;">{{ at }}</td>
              <td><img style="height:3rem;"src="https://stats.nba.com/media/img/teams/logos/{{abv[1]}}_logo.svg" alt="Card image cap">
              </td>
              <td  class="card-title result" style="position:relative;{% if game[7]=='L'%}color:red;{% else %}color:lightgreen;{% endif %}">{{ game[26]}} - {{ game[26] - game[27] }}
              </td>
            </tr>
          </table>
        {% endfor %}
        </div>
      </div>
      <div class="row d-flex justify-content-around flex-row">
        <div class="p-6 mx-auto">
         <img style="opacity:0.8;display:block;margin-top:10px;"src="data:image/png;base64, {{ graph.0 }}" /></div>
        <div class="p-6 mx-auto" >
      <img  style="opacity:0.8;display:block;margin-top:10px;" src="data:image/png;base64, {{ graph.1 }}" /> </div>
      </div>
      
      <h3 id="joueurs" class="whitetitle"> Stats des Joueurs </h3>
      {% include 'playerstats.html.twig' %}
      <h3 id="blessures" class="whitetitle"> Infirmerie </h3>
      <div id="injuredplayers" class="injuries">   
          
          <table class="table table-hover table-dark">
            <thead>
              <tr>
                <th scope="col"><img style="max-height:80px" src="https://stats.nba.com/media/img/teams/logos/{{teams.0.Stats.team_abv}}_logo.svg"/> Nom </th>
                <th scope="col"> Blessure</th>
                <th scope="col"> Statut</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for blesse in teams.0.injuries %}
                <td> {{blesse.player}} </td>
                <td> {{blesse.injury}} </td>
                <td> {{blesse.status}} </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <table class="table table-hover table-dark">
            <thead>
              <tr>
                <th scope="col"><img style="max-height:80px" src="https://stats.nba.com/media/img/teams/logos/{{teams.1.Stats.team_abv}}_logo.svg"/>
                Nom </th>
                    <th scope="col"> Blessure</th>
                <th scope="col"> Statut</th>
              </tr>
            </thead>
            <tbody>
              <tr>
              {% for blesse in teams.1.injuries %}
              
              <td> {{blesse.player}} </td>
              <td> {{blesse.injury}} </td>
              <td> {{blesse.status}} </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
      </div>

      <h3 id="highlights" class="whitetitle"> Highlights de la dernière rencontre </h3>
      <div class="youtube-player center-div">
          <figure style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; margin: 0px;">
          <iframe src="https://www.youtube.com/embed/{{game.videoId}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" loading="lazy"></iframe>
          </figure>
      </div>

      
        
      <h3 id="pronostics" class="whitetitle"> Partagez votre prono </h3>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .
 
      <div class="container" >
            <div class="row">
              <div class="col-12">
               
                <div class="comments-list bg-dark" style="color:white;border-radius:10px">

                {% for comment in comments %}
                    <div class="media" style="padding:15px;margin-bottom:5px;">
                
                          <a class="media-left" href="#">
                            <img src="http://lorempixel.com/40/40/sports/{{random(3)}}/">
                          </a>
                          <div class="media-body">
                              
                            <h4 class="media-heading user_name" style="margin-left:25px;"> {{comment.username}}:<span style="margin-left:40px;"> {{comment.bet}}</span></h4>
                           <p style="margin-left:25px;"> {{comment.message}} </p>
                            
                          </div>
                                                  <p class="pull-right"><small>{{ comment.PublishDate|date("H:i") }}</small></p>

                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
      </div>  
        
      <div class="container">
        {{ form(form) }}
      </div>
      <div class="row" style="opacity:0.9">
        <div class="col-6">
          <a class="twitter-timeline" href="{{teams.0.twitter}}" data-chrome="no-footer" data-tweet-limit="12">Twitter</a>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>

        <div class="col-6">
          <a class="twitter-timeline" href="{{teams.1.twitter}}" data-chrome="no-footer" data-tweet-limit="12">Twitter</a>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>

    </div>
   

  </div>
 
</div>        
  <div style="margin-top:200px;">    {% include 'matchs_de_la_nuit.html.twig' %}</div>
{% endblock %}

templates/playerstats.html.twig
<div id="player" class="playerstats " style="text-align:center;width:100%;">   
    <div class="btn-group center-div" role="group" style="display: inline-block;padding:20px;">
     {% include 'btngroup.html.twig' with {id:'player' ,name:'player5',btn_label:'Playoffs'} %}
     {% include 'btngroup.html.twig' with {id: 'player',name:'player',btn_label:'Saison'} %}
    </div>  
    <table class="table table-hover table-dark" style="text-align:left;">
    
      <thead>
      <tr syle="">
        <th scope="col"><img style="max-height:80px" src="https://stats.nba.com/media/img/teams/logos/{{teams.0.Stats.team_abv}}_logo.svg"/></th>
        <th scope="col"> Pts </th>
        <th scope="col"> %Tir</th>
        <th scope="col" class="mobilehide"> %3Pts</th>
        <th scope="col"> Reb</th>
        <th scope="col">Pd</th>
        <th scope="col" class="mobilehide"> PdB </th>
        <th scope="col" class="mobilehide"> Int </th>
        <th scope="col" class="mobilehide"> Ctr </th>
        <th scope="col" class="mobilehide"> +/- </th>
        <th scope="col" class="mobilehide"> Min </th>
        <th scope="col" class="mobilehide"> Matchs </th>

      </tr>
      </thead>
      <tbody>
    {% for joueur in joueurs_domicile %}
        <tr class="ty-compact-list1">
        <td><img class="small-picture" src="https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/1040x760/{{joueur.stats.id}}.png"/>{{joueur.stats.name}} </td>
        <td>{{joueur.stats.points}} 
        {# if joueur.stats.pointsRank < 50 %}({{joueur.stats.pointsRank}}){% endif #}
        </td>
        <td> {{joueur.stats.fg_pct}}
        {# if joueur.stats.fg_pctRank < 50 %}({{joueur.stats.fg_pctRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.three_fg_pct}}
        {# if joueur.stats.three_fg_pctRank < 50 %}({{joueur.stats.three_fg_pctRank}}){% endif #}</td>
        <td>{{joueur.stats.rebounds}}
        {# if joueur.stats.reboundsRank < 50 %}({{joueur.stats.reboundsRank}}){# endif #}</td>
        <td>{{joueur.stats.assists}}
        {# if joueur.stats.assistsRank < 50 %}({{joueur.stats.assistsRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.turnovers}}
        {# if joueur.stats.turnoversRank < 50 %}({{joueur.stats.turnoversRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.steals}}
        {# if joueur.stats.stealsRank < 50 %}({{joueur.stats.stealsRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.blocks}}
        {# if joueur.stats.blocksRank < 50 %}({{joueur.stats.blocksRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.plusminus}}{# if joueur.stats.plusminusRank < 50 %}({{joueur.stats.plusminusRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.minutes}}{# if joueur.stats.minutesRank < 50 %}({{joueur.stats.minutesRank}}){% endif #}</td>
        <td class="mobilehide">{{joueur.stats.games}}</td>

        
      </tr> 
    {% endfor %}
    <tr  colpan="6" class="show-more1 d-flex justify-content-center"><td style="text-align:center">Voir plus</td></tr>

    </tbody>    
    </table>

    <table class="table table-hover table-dark"  style="text-align:left;">
    <thead>
    <tr>
      <th scope="col"><img style="max-height:80px" src="https://stats.nba.com/media/img/teams/logos/{{teams.1.Stats.team_abv}}_logo.svg"/></th>
        <th scope="col"> Pts </th>
        <th scope="col"> %Tir</th>
        <th scope="col" class="mobilehide"> %3Pts</th>
        <th scope="col"> Reb</th>
        <th scope="col">Pd</th>
        <th scope="col" class="mobilehide"> PdB </t  h>
        <th scope="col" class="mobilehide"> Int </th>
        <th scope="col" class="mobilehide"> Ctr </th>
        <th scope="col" class="mobilehide"> +/- </th>
        <th scope="col" class="mobilehide"> Min </th>
        <th scope="col" class="mobilehide"> Matchs </th>
    </tr>
    </thead>
    <tbody>
    {% for joueur in joueurs_exterieur %}
     <tr class="ty-compact-list2">
        <td><img class="small-picture" src="https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/1040x760/{{joueur.stats.id}}.png"/>{{joueur.stats.name}} </td>
        <td>{{joueur.stats.points}} 
        {# if joueur.stats.pointsRank < 50 %}({{joueur.stats.pointsRank}}){% endif #}
        </td>
        <td> {{joueur.stats.fg_pct}}
        {# if joueur.stats.fg_pctRank < 50 %}({{joueur.stats.fg_pctRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.three_fg_pct}}
        {# if joueur.stats.three_fg_pctRank < 50 %}({{joueur.stats.three_fg_pctRank}}){% endif #}</td>
        <td>{{joueur.stats.rebounds}}
        {# if joueur.stats.reboundsRank < 50 %}({{joueur.stats.reboundsRank}}){# endif #}</td>
        <td>{{joueur.stats.assists}}
        {# if joueur.stats.assistsRank < 50 %}({{joueur.stats.assistsRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.turnovers}}
        {# if joueur.stats.turnoversRank < 50 %}({{joueur.stats.turnoversRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.steals}}
        {# if joueur.stats.stealsRank < 50 %}({{joueur.stats.stealsRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.blocks}}
        {# if joueur.stats.blocksRank < 50 %}({{joueur.stats.blocksRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.plusminus}}{# if joueur.stats.plusminusRank < 50 %}({{joueur.stats.plusminusRank}}){% endif #}</td>
        <td class="mobilehide"> {{joueur.stats.minutes}}{# if joueur.stats.minutesRank < 50 %}({{joueur.stats.minutesRank}}){% endif #}</td>
        <td class="mobilehide">{{joueur.stats.games}}</td>

        
      </tr> 
    {% endfor %}

    <tr class="show-more2 d-flex justify-content-center"><td>Voir plus</td></tr>
    </tbody>
    </table>
</div>






<div id="player5" class="playerstats" style="text-align:center;width:100%;">  
       <div class="btn-group center-div" role="group" style="display: inline-block;padding: 20px;">
          {% include 'btngroup.html.twig' with {id:'player5' ,name:'player5',btn_label:'Playoffs'} %}
          {% include 'btngroup.html.twig' with {id:'player5',name:'player',btn_label:'Saison'} %}
        </div>
        <div>
          <table class="table table-hover table-dark " style="text-align:left;">
           <thead>
            <tr>
              <th scope="col"><img style="max-height:80px" src="https://stats.nba.com/media/img/teams/logos/{{teams.0.stats.team_abv}}_logo.svg"/></th>
              <th scope="col"> Points </th>
              <th scope="col"> %Tir</th>
               <th scope="col" class="mobilehide"> %3Pts</th>
              <th scope="col"> Reb</th>
              <th scope="col">Pd</th>
              <th scope="col" class="mobilehide"> PdB </t  h>
              <th scope="col" class="mobilehide"> Int </th>
              <th scope="col" class="mobilehide"> Ctr </th>
              <th scope="col" class="mobilehide"> +/- </th>
              <th scope="col" class="mobilehide"> Min </th>
              <th scope="col" class="mobilehide"> Matchs </th>
            </tr>
           </thead>
           <tbody>
          {% for joueur in joueurs_domicile %}
          {% if joueur.stats5 is not null and joueur.stats5 is not empty %}
            <tr class="ty-compact-list3">
              <td><img class="small-picture" src="https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/1040x760/{{joueur.stats5.id}}.png"/>{{joueur.stats5.name}} </td>
              <td>{{joueur.stats5.points}} 
              {% if joueur.stats5.pointsRank < 50 %}({{joueur.stats5.pointsRank}}){% endif %}</td>
              <td> {{joueur.stats5.fg_pct}}
              {% if joueur.stats5.fg_pctRank < 50 %}({{joueur.stats5.fg_pctRank}}){% endif %}</td>
              <td> {{joueur.stats5.three_fg_pct}}
              {% if joueur.stats5.three_fg_pctRank < 50 %}({{joueur.stats5.three_fg_pctRank}}){% endif %}</td>
              <td>{{joueur.stats5.rebounds}}
              {% if joueur.stats5.reboundsRank < 50 %}({{joueur.stats5.reboundsRank}}){% endif %}</td>
              <td>{{joueur.stats5.assists}}
              {% if joueur.stats5.assistsRank < 50 %}({{joueur.stats5.assistsRank}}){% endif %}</td>
              <td> {{joueur.stats5.turnovers}}
              {% if joueur.stats5.turnoversRank < 50 %}({{joueur.stats5.turnoversRank}}){% endif %}</td>
              <td> {{joueur.stats5.steals}}
              {% if joueur.stats5.stealsRank < 50 %}({{joueur.stats5.stealsRank}}){% endif %}</td>
              <td> {{joueur.stats5.blocks}}
              {% if joueur.stats5.blocksRank < 50 %}({{joueur.stats5.blocksRank}}){% endif %}</td>
              <td> {{joueur.stats5.plusminus}}{% if joueur.stats5.plusminusRank < 50 %}({{joueur.stats5.plusminusRank}}){% endif %}</td>
              <td> {{joueur.stats5.minutes}}{% if joueur.stats5.minutesRank < 50 %}({{joueur.stats5.minutesRank}}){% endif %}</td>
              <td>{{joueur.stats5.games}}</td>
            </tr>
        
          {% endif %}
         {% endfor %}

            <tr class="show-more3 d-flex justify-content-center"><td>Voir plus</td></tr>         </tbody>    
         </table>

         <table class="table table-hover table-dark" style="text-align:left;">
         <thead>
          <tr>
            <th scope="col"><img style="max-height:80px" src="https://stats.nba.com/media/img/teams/logos/{{teams.1.stats.team_abv}}_logo.svg"/></th>
            <th scope="col"> Points </th>
            <th scope="col"> %Tir</th>
            <th scope="col" > %3pts </th>
            <th scope="col"> Reb</th>
            <th scope="col">Pd</th>
            <th scope="col"> PdB </t  h>
            <th scope="col"> Int </th>
            <th scope="col"> Ctr </th>
            <th scope="col"> +/- </th>  
            <th scope="col"> Minutes </th>
            <th scope="col"> Matchs </th>
          </tr>
         </thead>
         <tbody>
          {% for joueur in joueurs_exterieur %}
          {% if joueur.stats5 is not null and joueur.stats5 is not empty %}

            <tr class="ty-compact-list4">
              <td><img class="small-picture" src="https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/1040x760/{{joueur.stats5.id}}.png"/>{{joueur.stats5.name}}</td>
              <td>{{joueur.stats5.points}} 
              {% if joueur.stats5.pointsRank < 50 %}({{joueur.stats5.pointsRank}}){% endif %}</td>
              <td> {{joueur.stats5.fg_pct}}
              {% if joueur.stats5.fg_pctRank < 50 %}({{joueur.stats5.fg_pctRank}}){% endif %}</td>
              <td> {{joueur.stats5.three_fg_pct}}
              {% if joueur.stats5.three_fg_pctRank < 50 %}({{joueur.stats5.three_fg_pctRank}}){% endif %}</td>
              <td>{{joueur.stats5.rebounds}}
               
              {% if joueur.stats5.reboundsRank < 50 %}({{joueur.stats5.reboundsRank}}){% endif %}</td>
              <td>{{joueur.stats5.assists}}
              {% if joueur.stats5.assistsRank < 50 %}({{joueur.stats5.assistsRank}}){% endif %}</td>
              <td> {{joueur.stats5.turnovers}}
              {% if joueur.stats5.turnoversRank < 50 %}({{joueur.stats5.turnoversRank}}){% endif %}</td>
              <td> {{joueur.stats5.steals}}
              {% if joueur.stats5.stealsRank < 50 %}({{joueur.stats5.stealsRank}}){% endif %}</td>
              <td> {{joueur.stats5.blocks}}
              {% if joueur.stats5.blocksRank < 50 %}({{joueur.stats5.blocksRank}}){% endif %}</td>
              <td> {{joueur.stats5.plusminus}}{% if joueur.stats5.plusminusRank < 50 %}({{joueur.stats5.plusminusRank}}){% endif %}</td>      
               <td> {{joueur.stats5.minutes}}{% if joueur.stats5.minutesRank < 50 %}({{joueur.stats5.minutesRank}}){% endif %}</td>
              <td>{{joueur.stats5.games}}</td>
            </tr> 
            {% endif %}
          {% endfor %}

          <tr class="show-more4 d-flex justify-content-center"><td>Voir plus</td></tr>         </tbody>
         </table>
        </div> 
</div>

templates/signup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription
{% endblock %}


{% block body %}
{% include 'matchs_de_la_nuit.html.twig' %}

<div class="wrapper fadeInDown">
  <div id="formContent" class="bg-secondary">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
        <h3 class="whitetitle"> Inscription </h3>
    </div>

 
     <!-- Login Form -->
    {{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.username, { 'label': 'Nom d\'utilisateur' }) }}
    {{ form_row(form.password, { 'label': 'Mot de passe' }) }}
     {% if error != "" %}
     <p class="alert-danger "> {{ error}} </p>
{% endif %}

   <span class="bg-success"> {{ form_row(form.save, { 'label': 'Creer mon compte' }) }}</span>
    {{ form_end(form) }}
 
  </div>
</div>
{% endblock %}